// Generated by `bun run api:gen` (openapi-typescript) — do not hand-edit.
// This stub keeps `tsc -b` happy in fresh checkouts before codegen has run.
// Run `bun install && bun run api:gen` to replace it with the real types.

export type paths = Record<string, never>;
export type components = Record<string, never>;
